### ISSUE TITLE
Home-Link auch auf Home anzeigen

### ISSUE THREAD

**Issue by L3P3** [Ricacatalina/Schulwebsite#14]
Auf anderen Seiten ist oben der Link auch noch zu sehen.

**Comment by Ricacatalina** [comment]
Habe den Home-Link auf der Startseite hinzugefügt und die Links, die auf die selbe Seite führen entfernt.

**Comment by L3P3** [comment]
Ja, besser erstmal. Mach aber bitte noch den :hover-Effekt weg, also benutz für die "aktiven" Einträge mal span- statt a-Elemente. Oder häng die active-Klasse gleich an das li-Element und lass bei den aktiven Einträgen das a-Element ganz weg.

**Comment by L3P3** [comment]
Also für den aktiven Eintrag `<li class=active>Seitentitel</li>` und die inaktiven so wie jetzt.

**Comment by Ricacatalina** [comment]
Habe ich gemacht, aber dann ist das Fach aus der Zeile gerutscht. Hat irgendwie nicht gut funktoniert.

**Comment by Ricacatalina** [comment]
Deshalb habe ich das erstmal so gelassen.

**Comment by L3P3** [comment]
Ah, wegen `padding` beim a-Element darin vielleicht. Probier mal stattdessen dem li-Element das Padding zu geben, damit das Layout nicht davon abhängig ist, ob da ein Link drin ist oder nicht.

**Comment by L3P3** [comment]
Würde mir das gerne sonst gleich mal ansehen, lass uns dann mal per Slack reden.
