### ISSUE TITLE
Webseite ohne Server?

### ISSUE THREAD

**Issue by LFF5644** [Ricacatalina/Schulwebsite#5]
die Webseite läuft derzeit local ein webserver ist sehr empfolen ich empfele dir [rtjscomp](https://github.com/L3P3/rtjscomp) das nutze ich selbst auf [meiner webseite](https://lff.l3p3.de) und ermöglicht dir noch zusätzlich einen serverseitigen code auszufüren also backend ist sowas wie php nur besser ;) 
Grüsse Lando

**Comment by L3P3** [comment]
Guck aber vorher auf MEINE Website: https://l3p3.de die ist nämlich viel besser.

**Comment by LFF5644** [comment]
HALLO, KEINE EIGEN-WERBUNG!

**Comment by L3P3** [comment]
https://rica-schule.l3p3.de/

**Comment by L3P3** [comment]
https://github.com/Ricacatalina/Schulwebsite/commit/dd8c1b94d7d1769f4ae6c1483628ca1500d45dac
